config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :meetings
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'meetings#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  ################# validations ##############
  validates :title, presence: true
  validates :duration, presence: true
  validates :start_time, presence: true
  validates :password, presence: true
  validates :description, presence: true
  ################# Relationships ##############
  belongs_to :user, optional: true
  ################# state machine ##############
  include AASM
  aasm do
    state :proposed, initial: true
    state :confirmed

    event :confirm do
      transitions from: :proposed, to: :confirmed
    end
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user = current_user

    respond_to do |format|
      if @meeting.save
        format.html {redirect_to meeting_url(@meeting), notice: "Meeting was successfully created."}
        format.json {render :show, status: :created, location: @meeting}
      else
        format.html {render :new, status: :unprocessable_entity}
        format.json {render json: @meeting.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html {redirect_to meeting_url(@meeting), notice: "Meeting was successfully updated."}
        format.json {render :show, status: :ok, location: @meeting}
      else
        format.html {render :edit, status: :unprocessable_entity}
        format.json {render json: @meeting.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy

    respond_to do |format|
      format.html {redirect_to meetings_url, notice: "Meeting was successfully destroyed."}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def meeting_params
    params.require(:meeting).permit(:title, :description, :start_time, :duration, :password)
  end
end

app/views/meetings/_form.html.erb
<div class="row m-2">
  <div class="col-lg-4 offset-lg-4">
    <%= form_with(model: meeting) do |form| %>
      <% if meeting.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

          <ul>
            <% meeting.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :title, class: 'form-label' %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :description, class: 'form-label' %>
        <%= form.text_field :description, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :start_time, class: 'form-label' %>
        <%= form.datetime_field :start_time, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :duration, class: 'form-label' %>
        <%= form.number_field :duration, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :password, class: 'form-label' %>
        <%= form.text_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <% if meeting.persisted? %>
          <div class="float-end">
            <%= link_to 'Destroy', meeting, method: :delete, class: "text-danger", data: {confirm: 'Are you sure?'} %>
          </div>
        <% end %>

        <%= form.submit class: 'btn btn-primary' %>

        <% if meeting.persisted? %>
          <%= link_to "Cancel", meeting, class: "btn btn-link" %>
        <% else %>
          <%= link_to "Cancel", meetings_path, class: "btn btn-link" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/meetings/_meeting.html.erb
<div id="<%= dom_id meeting %>">
  <p>
    <strong>Title:</strong>
    <%= meeting.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= meeting.description %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= meeting.start_time %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= meeting.duration %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= meeting.password %>
  </p>

</div>

app/views/meetings/edit.html.erb
<h1 class="text-center">Edit Meeting</h1>

<%= render 'form', meeting: @meeting %>

app/views/meetings/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Meetings</h1>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_meeting_path, class: 'btn btn-primary' do %>
    Add New Meeting
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Title</th>
            <th>Start time</th>
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @meetings.each do |meeting| %>
        <%= content_tag :tr, id: dom_id(meeting), class: dom_class(meeting) do %>
          

                      <td><%= meeting.title %></td>
                      <td><%= meeting.start_time %></td>

          
            <td><%= link_to 'Show', meeting %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/meetings/new.html.erb
<h1 class="text-center">New meeting</h1>

<%= render 'form', meeting: @meeting %>

app/views/meetings/show.html.erb
<div class="page-header">
  <h1 class="text-center">Show meeting</h1>
</div>
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <table class="table ">
        <tbody>
        <tr>
          <th scope="row">Title:</th>
          <td><%= @meeting.title %></td>
        </tr>
        <tr>
          <th scope="row">Description:</th>
          <td><%= @meeting.description %></td>
        </tr>
        <tr>
          <th scope="row">Start time:</th>
          <td><%= @meeting.start_time %></td>
        </tr>
        <tr>
          <th scope="row">Duration:</th>
          <td><%= @meeting.duration %></td>
        </tr>
        <tr>
          <th scope="row">status:</th>
          <td><%= @meeting.aasm_state %></td>
        </tr>
        </tbody>
      </table>
      <%= link_to meetings_path, class: 'btn btn-outline-dark' do %>
        Back
      <% end %>
      <%= link_to edit_meeting_path(@meeting), class: 'btn btn-outline-primary' do %>
        Edit
      <% end %>
    </div>
  </div>
</div>